config/routes.rb
Rails.application.routes.draw do
  resources :actor_movies
  resources :movies
  resources :actors
  resources :directors
  resources :addresses
  resources :categories

  get '/persons/new', to: 'persons#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :actormovies
  has_many :movies, through: :actormovies
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:first_name, :last_name, :birthday, :description)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :actor_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :actor_last_name %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, id: :actor_birthday %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :actor_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthday</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.first_name %></td>
        <td><%= actor.last_name %></td>
        <td><%= actor.birthday %></td>
        <td><%= actor.description %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @actor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @actor.last_name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @actor.birthday %>
</p>

<p>
  <strong>Description:</strong>
  <%= @actor.description %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>